name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'node' # This will use the latest stable Node.js version
        
    - run: node -v # This line is just to print the Node.js version to the log
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
